### PR TITLE
Fix bug where env export had trailing \r on windows

### PR DESCRIPTION
**Pull request by jeremiahsnapp**
For context, similar issues were seen in the agent and fixed in the following PRs.

https://github.com/buildkite/agent/pull/569
https://github.com/buildkite/agent/pull/630

### CODE REVIEW

**Comment by toolmantim** [comment]
Thanks so much! 🙏🏼

**Comment by lox** [comment]
I'd love to help figure out what the underlying problem is @jeremiahsnapp, there definitely shouldn't be trailing carriage returns in environment! Fixing them in all the plugins will result in some epic whack-a-mole. What agent version are you on?

**Comment by jeremiahsnapp** [comment]
Hi @lox, I'm glad you asked me to dig deeper. I misunderstood the cause of the problem. The `\r` is actually coming from the fact that the Windows version of `sort` is getting used instead of the GNU `sort` that comes with Git for Windows.

The `sort` command is getting called here:

https://github.com/buildkite-plugins/docker-login-buildkite-plugin/blob/master/hooks/pre-command#L10

**Search order**

```
Administrator@EC2AMAZ-61SO5I5  ~
$ which -a sort
/c/Windows/system32/sort
/usr/bin/sort
```

**Windows `sort`**

```
Administrator@EC2AMAZ-61SO5I5  ~
$ echo hello | sort | od -c
0000000   h   e   l   l   o  \r  \n
0000007
```

**GNU `sort`**

```
Administrator@EC2AMAZ-61SO5I5  ~
$ echo hello | /usr/bin/sort | od -c
0000000   h   e   l   l   o  \n
0000006
```

I am fixing my environment now by prepending `C:\Program Files\Git\usr\bin` to the system's `PATH`.

Please feel free to revert this PR or let me know if you want me to submit a PR that reverts it. Sorry for the trouble.

**Comment by toolmantim** [comment]
Ah, I’m surprised you got so far with the whole setup with the Windows binaries. Did it work with this fix? Or did you have other problems that you needed to switch to the GNU binaries for?

We’ll probably revert this, sorry for not spotting it in review.

**Comment by lox** [comment]
Ugh, yeah this is a huge problem on windows. Don't even get me started on the Powershell implementations of `wget` and `curl`. 

Perhaps we could detect this and warn people. At the very least we should document it! Sorry you ran into that @jeremiahsnapp.

**Comment by jeremiahsnapp** [comment]
@toolmantim @lox I’ve had to work through some other issues but this has been the only one caused by the unexpected use of Windows binaries.

This PR fixed the issue for me by removing the unexpected \r but obviously now we know that’s not the best solution. I fixed my problem today by putting the path to the GNU binaries before the rest of the PATH.

As an aside, I’m a little surprised that Git for Windows didn’t do this for me. I used the ‘/GitAndUnixToolsOnPath’ install option when installing Git for Windows which warns that it will override some Windows commands like “sort” and “find” with the GNU versions. But in reality the installer puts the GNU binaries path at the end of the existing PATH so it doesn’t actually override the Windows binaries. Strange right? I even looked at the Git for Windows installer code and it looks pretty clear to me that it appends the new path instead of prepend. Anyway, problem solved as far as I’m concerned.

**Comment by toolmantim** [comment]
Thanks for the full context @jeremiahsnapp. So strange they'd order the PATH that way!

**Pull request merged**
